---
# tasks file for loki

- name: Deploy Loki service
  ansible.builtin.include_tasks:
    file: "deploy.yml"
    apply:
      tags: loki_deploy
  tags: loki_deploy

- name: Uninstall Loki service
  ansible.builtin.include_tasks:
    file: "uninstall.yml"
    apply:
      tags:
        - loki_uninstall
        - never
  tags:
    - loki_uninstall
    - never
